import type { Metadata } from "next";
import "../globals.css";
import FooterNav from "@/components/navigations/footer-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="  bg-black ">
      <div className="max-w-3xl w-full flex flex-col justify-end min-h-screen bg-background mx-auto relative ">
        {children}
        <FooterNav />
      </div>
    </div>
  );
}
